[package]
name = "projectloupe"
version = "0.1.0"
edition = "2021"

[dependencies]
rexif = "0.7"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
rayon = "1.7"
